### ISSUE TITLE
The update cron job fails 

### ISSUE THREAD

**Issue by atomicwrites** [disconn3ct/tiny_tiny_rss-openshift-quickstart#24]
The server was working correctly for the first few days but then it stopped updating. I SSHed in and ran `update.php --feeds` wich succeeded and the new articles were visible in the web UI. Then I saw that the cron job logs output to `$OPENSHIFT_PHP_LOG_DIR/rss_update.log`. This is the contents of the log:

```
Failed loading /opt/rh/php54/root/usr/lib64/php/modules/opcache.so:  /opt/rh/php54/root/usr/lib64/php/modules/opcache.so: undefined symbol: zend_new_interned_string
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/ldap.so' - /usr/lib64/php/modules/ldap.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd.so' - /usr/lib64/php/modules/mysqlnd.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd_mysql.so' - /usr/lib64/php/modules/mysqlnd_mysql.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/mysqlnd_mysqli.so' - /usr/lib64/php/modules/mysqlnd_mysqli.so: cannot open shared object file: No such file or directory in Unknown on line 0
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib64/php/modules/pdo_mysqlnd.so' - /usr/lib64/php/modules/pdo_mysqlnd.so: cannot open shared object file: No such file or directory in Unknown on line 0
Tiny Tiny RSS was unable to start properly. This usually means a misconfiguration or an incomplete upgrade.
Please fix errors indicated by the following messages:

 * PHP version 5.4.0 or newer required.

You might want to check tt-rss wiki or the forums for more information.
Please search the forums before creating new topic for your question.
```
There's no time stamp but stating the file confirms that the job is running regularly, always with the same output. I haven't messed with anything other than what's configurable in the setting interface. Any help fixing this is appreciated.

**Comment by caglarkoksal** [comment]
Not sure what caused your problem but this cron script has been working for me for quite sometime now - maybe worth a try?

> #!/bin/bash
> $OPENSHIFT_REPO_DIR/php/update.php --feeds &> $OPENSHIFT_LOG_DIR/rss_update.log

**Comment by disconn3ct** [comment]
This repo can be considered abandoned - openshift was such a mess I stopped arguing with it and wandered off. I'll still take pull requests if anyone wants to contribute, or check out some of the forks that might be more up to date.

**Comment by bilderbuchi** [comment]
Hm, sad to hear that. What was your experience with openshift? To this day I am heavily using a ttrss instance that basically haven't touched for a year plus. The only strange thing is that it's slowly filling up it's disk space, growing to what I feel is a way too large size for the article retain timeout that is in place.

**Comment by caglarkoksal** [comment]
@bilderbuchi I do not want to spam here as the project is discontinued, but, if you feel like making a fresh start with tt-rss on openshift, I just uploaded my own guide [here](http://www.caglarkoksal.com/post-draft/install-ttrss-openshift/).

**Comment by atomicwrites** [comment]
@caglarkoksal thanks, I'll give this a shot, although I'm currently looking for a good native reader, TTRSS's web UI is a pain especially on Mobil.

**Comment by szpak** [comment]
Btw, @Aventura5, there are [2](https://play.google.com/store/apps/details?id=org.fox.ttrss&hl=en) Android [clients](https://play.google.com/store/apps/details?id=org.ttrssreader&hl=en) for ttrss which give better user experience than a web UI (if you're an Android user).

**Comment by atomicwrites** [comment]
Thank @szpak, I tried using TTRSS-Reader but the readability plugging doesn't work, I just get the truncated version. The other one I haven't tried because it's paid.

**Comment by bilderbuchi** [comment]
Iirc, the paid one is made by the maintainer/creator of ttrss, though (Andrei dolgov).

**Comment by bilderbuchi** [comment]
So @caglarkoksal and others: Has anybody successfully transitioned away from the end-of-life'd openshift v2? 
I tried to migrate my existing v2 project to v3 yesterday, but let's just say afer drowning in error message and confusing documentation for several hours, I just gave up.

Maybe it's feasible to start a new v3 application, and just migrate the feeds via OPML, but honestly the documentation complexity makes me think that I need a CS degree to understand how to build something working out of the PHP and postgresql templates...

**Comment by bilderbuchi** [comment]
Failing that, @disconn3ct where did you ttrss installation wander off to? something free?

**Comment by disconn3ct** [comment]
Unfortunately I gave up on free and moved over to the evil AWS empire. The instance does more things than just this but it's also $.
